### PR TITLE
"check" command

### LINKED ISSUE #49: checking links
> When working on notes
> I want to be notified about broken TikiLinks
> So that my Tikibase is always in a consistent state.

```cucumber
Scenario: working internal Markdown link

Scenario: working internal HTML link

Scenario: internal Markdown link to a missing file

Scenario: internal Markdown link to a missing anchor within an existing file

Scenario: internal HTML link to a missing file

Scenario: internal HTML link to a missing anchor within an existing file

Scenario: broken external Markdown link

Scenario: broken external HTML link
```

### PR DESCRIPTION
**Pull request by kevgo**
resolves #49

### CODE REVIEW

File: checklinks/link_target_collection_test.go [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+	ltc := make(linkTargetCollection)
+	err := ltc.Add("1.md")
+	assert.Nil(t, err)
+	err = ltc.Add("1.md")
+	assert.NotNil(t, err)
+}
+
+func TestLinkTargetCollection_String(t *testing.T) {
+	linkTargets := linkTargetCollection{}
+	linkTargets.Add("one")
```
Comment (golangcibot) [inline checklinks/link_target_collection_test.go]: Error return value of `linkTargets.Add` is not checked (from `errcheck`)

File: checklinks/link_target_collection_test.go [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+	linkTargets.Add("two")
```
Comment (golangcibot) [inline checklinks/link_target_collection_test.go]: Error return value of `linkTargets.Add` is not checked (from `errcheck`)

File: checklinks/link_target_collection_test.go [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+	ltc := make(linkTargetCollection)
+	err := ltc.Add("1.md")
+	assert.Nil(t, err)
+	err = ltc.Add("1.md")
+	assert.NotNil(t, err)
+}
+
+func TestLinkTargetCollection_String(t *testing.T) {
+	ltc := linkTargetCollection{}
+	ltc.Add("one")
```
Comment (golangcibot) [inline checklinks/link_target_collection_test.go]: Error return value of `ltc.Add` is not checked (from `errcheck`)

File: checklinks/link_target_collection_test.go [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+	ltc.Add("two")
```
Comment (golangcibot) [inline checklinks/link_target_collection_test.go]: Error return value of `ltc.Add` is not checked (from `errcheck`)
